### ISSUE TITLE
 How do I resolve esh-tp dependency?

### ISSUE THREAD

**Issue by satish-nikam** [maggu2810/shk#3]
Hi Markus, Thanks a lot for this project. 

Could you please provide more instructions on setting this project? Which karaf version I should use?

I built this project using "mvn clean install" and then executed following command on karaf console:
karaf@root()> feature:repo-add mvn:org.eclipse.smarthome/karaf/0.8.0.b5/xml/features

Then I tried installing esh-base, but got following error. How do I resolve esh-tp dependency? 
karaf@root()> feature:install esh-base
Error executing command: Can't install feature esh-base/0.0.0:  
No feature named 'esh-tp' with version '0.0.0' available

**Comment by maggu2810** [comment]
After you have cloned this repo you start he build using <code>mvn clean install</code>

After that a custom distribution that contains the ESH features (+ feature-repos) has already been created.
You can start that custom distribution using:
`distributions/base/target/assembly/bin/karaf`

**Comment by satish-nikam** [comment]
Thanks a lot for quick response. Now I am able to launch ESH in karaf.

**Comment by maggu2810** [comment]
So, what's missing to close that issue?

**Comment by satish-nikam** [comment]
Nothing. Closing the issue. Thanks again.
