### ISSUE TITLE
How to enable mdns discovery for ESH running using karaf?

### ISSUE THREAD

**Issue by satish-nikam** [maggu2810/shk#4]
I included following features in karaf feature.xml file, but I could not get mdns discovery working for ESH running using karaf.
<feature>esh-tp-jmdns</feature>
<feature>esh-io-transport-mdns</feature>

But from eclipse IDE, I am able to get mdns working by enabling OSGI bundles javax.jmdns and org.eclipse.smarthome.io.transport.mdns. This helps me to discover ESH in the network.

Do we need to add any other maven dependency in feature.xml for this?

**Comment by maggu2810** [comment]
Hm, I think this should work.
Have you tested all your interfaces and all IP addresses of your interfaces (e.g. IPv4 vs. IPv6)?
Currently only one is used.
Perhaps related to: https://github.com/eclipse/smarthome/issues/577

**Comment by satish-nikam** [comment]
I checked both ipv4 and ipv6 interfaces. When run inside eclipse IDE, I see "_smarthome-server._tcp.local" under ipv4 interface. But when run using karaf, I donot see any.

**Comment by maggu2810** [comment]
Tested it myself. You are right, there is nothing announced.
I assume this needs to be debugged.

**Comment by satish-nikam** [comment]
Great. Thanks. Meanwhile I will check if this works in OpenHAB2-Karaf.

**Comment by maggu2810** [comment]
The org.eclipse.smarthome.io.rest bundle contains in the package org.eclipse.smarthome.io.rest.internal the class MDNSAnnouncer.
I think this one needs to be enabled.

**Comment by maggu2810** [comment]
This implementation needs a system property for the HTTP port to be set:
https://github.com/eclipse/smarthome/blob/b5f3305277883cfaf944ae3d8d15dcc19dc7a6c4/bundles/io/org.eclipse.smarthome.io.rest/src/main/java/org/eclipse/smarthome/io/rest/internal/MDNSAnnouncer.java#L49

As we are using the configuration admin in Karaf this property is not set.
openHAB sets this property.

**Comment by satish-nikam** [comment]
I explicitly added org.eclipse.smarthome.io.rest bundle and also set property org.osgi.service.http.port in a newly created file distributions/base/target/assembly/etc/org.ops4j.pax.web.cfg. But no luck.

Status of various relevant bundles and features is shown below. I modified your code to use v0.8.0  instead of 0.8.0.b5.

karaf@root()> bundle:list | grep -i rest
137 | Active |  80 | 0.8.0                 | Eclipse SmartHome Automation REST API
156 | Active |  80 | 0.8.0                 | Eclipse SmartHome REST Interface Bundle
157 | Active |  80 | 0.8.0                 | Eclipse SmartHome Core REST API
158 | Active |  80 | 0.8.0                 | Eclipse SmartHome Sitemap REST API
159 | Active |  80 | 0.8.0                 | Eclipse SmartHome SSE REST API
218 | Active |  80 | 1.8.0.SNAPSHOT        | shk :: Bundles :: IO :: REST Docs

karaf@root()> bundle:list | grep -i mdns
 30 | Active |  80 | 3.5.0                 | JmDNS

karaf@root()> feature:list | grep -i mdns
esh-tp-jmdns                              | 0.8.0            |          | Started     | karaf-tp-0.8.0  
smartalyse-mdns                        | 1.8.0.SNAPSHOT   |          | Started     | base-1.8-SNAPSHOT 
esh-io-transport-mdns                | 0.8.0            |          | Started     | karaf-0.8.0

**Comment by maggu2810** [comment]
As already stated in the comment above, the current implementation of the MDNSAnnouncer checks for a **system property**. It does not use a configuration property.

For Karaf and the usage of Pax Web we also should track the configuration admin.
I have not much time, but I started to give it a try yesterday (to watch for the configuration properties):
https://github.com/maggu2810/shk/compare/master...shk-io-mdns-web?expand=1

I will implement this if I can find some time.
IMHO using the system property only is not correct (why should we depend on the property if its not necessary).

**Comment by satish-nikam** [comment]
Sorry, I missed "**system property**" from your response. I set the system property as required and now it is working fine. I am closing this issue.

**Comment by maggu2810** [comment]
You are welcome!
I still think it is wrong to rely on that the port is set by a system property.
If my implementation is ready, I will discuss if it could be merged to upstream / integrated into the org.eclipse.smarthome.io.rest bundle.

**Comment by maggu2810** [comment]
I have created a bundle that could handle the properties of the configuration admin, too: https://github.com/maggu2810/shk/commit/ada83b2dfdd87d7fc41c38fe5121509c6ff8ffcd
So, if you use it, there is no need to set the system properties at all.
